# Numpy

### Importation des librairies

In [63]:
import numpy as np
import random

### Create an array

In [11]:
mon_array1 = np.array([])
print("array1 : ",mon_array1,type(mon_array1))
mon_array1.shape #Ici tableau vide => 0 dimension

array1 :  [] <class 'numpy.ndarray'>


(0,)

### avec des valeurs : en 1D

In [12]:
mon_array2 = np.array([1,2,3,4,5])
print("mon_array2 : ", mon_array2, type(mon_array2))
mon_array2.shape

mon_array2 :  [1 2 3 4 5] <class 'numpy.ndarray'>


(5,)

### avec des valeurs : en 2D

In [13]:
mon_array3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("mon_array3 : ", mon_array3, type(mon_array3))
mon_array3.shape # Ici 2 lignes, 5 colonnes

mon_array3 :  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] <class 'numpy.ndarray'>


(2, 5)

### avec des valeurs : en 3D

In [14]:
mon_array4 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print("mon_array4 : ", mon_array4, type(mon_array4))
mon_array4.shape

mon_array4 :  [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]] <class 'numpy.ndarray'>


(2, 2, 5)

### Numpy avec valeurs random

In [61]:
random_array = np.random.randint(low = [10,100], high = [99,1000], size = (4, 2 ,2))
print("random_array de shape (",random_array.shape,") : \n",random_array,type(random_array))

nom_array = np.random.rand(2,2)
print("\n nom_array de shape (",nom_array.shape,") : \n",nom_array,type(nom_array))

random_array de shape ( (4, 2, 2) ) : 
 [[[ 18 957]
  [ 18 136]]

 [[ 51 997]
  [ 32 310]]

 [[ 70 256]
  [ 37 301]]

 [[ 21 580]
  [ 95 454]]] <class 'numpy.ndarray'>

 nom_array de shape ( (2, 2) ) : 
 [[0.27886438 0.11742865]
 [0.09735556 0.27722016]] <class 'numpy.ndarray'>


### tableau de zéros

In [65]:
zero_array = np.zeros(shape=(2, 3))
print("zero_array de shape ",zero_array.shape," : \n",zero_array,type(zero_array))

zero_array de shape  (2, 3)  : 
 [[0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.ndarray'>
45


### Création avec des données spécifiques

In [67]:
spe_array = np.arange(start = 0, stop = 100, step = 10)
print("spe_array = ",spe_array)
print (random.)

spe_array =  [ 0 10 20 30 40 50 60 70 80 90]


### Matrice identité

In [70]:
identity_array = np.identity(5)
print("identity_array:\n", identity_array)
print(np.eye(4))

identity_array:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
