# Manupule Array

In [45]:
import numpy as np
import random

### Create  array

In [2]:
mon_array = np.array([1,2,3,4,5])
print("mon_array = ",mon_array)

mon_array =  [1 2 3 4 5]


### Ajout de valeurs en array en 1D

In [7]:
appended_array = np.append(mon_array, np.array([1, 2, 3]))

print("appended_array : \n",appended_array)

appended_array : 
 [1 2 3 4 5 1 2 3]


### Ajout de valeurs en array en 2D

In [22]:
mon_array2d = np.random.randint(0,100, size = (3 ,2))
print("mon_array2d : \n", mon_array2d)

#Ajout
appended_array2d = np.append(mon_array2d, [[12,12],[12,12]],axis=0)
print(" \n appended_array2d : \n", appended_array2d)

appended_bis_array2d = np.append(appended_array2d, [[12,12],[12,12],[12,12],[12,12],[12,12]],axis=1)
print(" \n appended_bis_array2d : \n", appended_bis_array2d)

mon_array2d : 
 [[ 1 82]
 [67 26]
 [88 95]]
 
 appended_array2d : 
 [[ 1 82]
 [67 26]
 [88 95]
 [12 12]
 [12 12]]
 
 appended_bis_array2d : 
 [[ 1 82 12 12]
 [67 26 12 12]
 [88 95 12 12]
 [12 12 12 12]
 [12 12 12 12]]


### Suppression de données

In [42]:
mon_array = np.random.randint(0,100,10)
print("mon_array : \n", mon_array)

mon_array_removed = np.delete(mon_array, [2,4,6,8])
print("\n mon_array_removed : \n", mon_array_removed)

mon_array : 
 [86 72 91 58  1 43 99  6 36 20]

 mon_array_removed : 
 [86 72 58 43  6 20]


### 

In [103]:
random.seed(0)

random_array = np.random.randint(10,20, size = (3 ,2))
print("random_array : \n", random_array)
reshaped_array = np.reshape(random_array, newshape=(2,3))
print("\n reshaped_array : \n", reshaped_array)

random_array : 
 [[12 10]
 [17 18]
 [12 11]]

 reshaped_array : 
 [[12 10 17]
 [18 12 11]]


### Passage de 2D en 1D

In [104]:
new_shape_array = np.reshape(random_array, (6))
print("new_shape_array = ", new_shape_array)

new_shape_array =  [12 10 17 18 12 11]


### Passage de 1D en 2D

In [105]:
random_array2 = np.random.randint(10,20,10)
print("random_array2 : \n", random_array2)
reshaped_array2 = np.reshape(random_array2,(5,2))
print("\n reshaped_array2 : \n", reshaped_array2)

random_array2 : 
 [14 16 17 19 13 19 13 11 11 19]

 reshaped_array2 : 
 [[14 16]
 [17 19]
 [13 19]
 [13 11]
 [11 19]]


### Dimension -1 dans un reshape

In [108]:
random_array3 = np.random.randint(10,20,(4,2))
print("random_array3 : \n", random_array3)
reshaped_array3 = random_array3.reshape(-1,4)
print("reshaped_array3 : \n", reshaped_array3)

random_array3 : 
 [[15 16]
 [18 15]
 [19 18]
 [10 16]]
reshaped_array3 : 
 [[15 16 18 15]
 [19 18 10 16]]


### Flatering array 2D

In [109]:
print(np.ndarray.flatten(random_array3))

[15 16 18 15 19 18 10 16]


In [111]:
print(np.matrix.flatten(random_array3))

[15 16 18 15 19 18 10 16]


### Triage des tableaux

In [114]:
random_array4 = np.random.randint(10,20,(4,3))
print("random_array4 : \n", random_array4)

arranged_array = np.sort(random_array4, axis = 0)
print("\n arranged_array : \n", arranged_array)

arranged_array2 = np.sort(random_array4, axis = 1)
print("\n arranged_array2 : \n", arranged_array2)

random_array4 : 
 [[11 13 19]
 [11 12 16]
 [14 15 19]
 [10 18 14]]

 arranged_array : 
 [[10 12 14]
 [11 13 16]
 [11 15 19]
 [14 18 19]]

 arranged_array2 : 
 [[11 13 19]
 [11 12 16]
 [14 15 19]
 [10 14 18]]


### Rotation d'array

In [120]:
rotate_array = np.array([[1, 2], [3, 4], [5, 6]])  
print("rotate_array:\n", rotate_array)

print("\n rotation_sens_antihoraire:\n", np.rot90(rotate_array, k=1 , axes=(0,1))) # k le nombre de rotations et (0,1) pour la rotation 
print("\n rotation_sens_horaire:\n", np.rot90(rotate_array, k=1 , axes=(1,0)))
print("\n rotation_sens_antihoraire x2:\n", np.rot90(rotate_array, k=2 , axes=(0,1))) 
print("\n rotation_sens_horaire x2:\n", np.rot90(rotate_array, k=2 , axes=(1,0)))

rotate_array:
 [[1 2]
 [3 4]
 [5 6]]

 rotation_sens_antihoraire:
 [[2 4 6]
 [1 3 5]]

 rotation_sens_horaire:
 [[5 3 1]
 [6 4 2]]

 rotation_sens_antihoraire x2:
 [[6 5]
 [4 3]
 [2 1]]

 rotation_sens_horaire x2:
 [[6 5]
 [4 3]
 [2 1]]
