# Opérations sur les Matrices

In [1]:
import numpy as np

### Addition et soustraction de matrices

In [2]:
mat1 = np.random.randint(1,10,(3,3))
print("mat1 : \n", mat1)
mat2 = np.random.randint(11,20,(3,3))
print("\n mat2 : \n", mat2)

mat1 : 
 [[4 4 6]
 [7 1 7]
 [9 5 9]]

 mat2 : 
 [[15 15 11]
 [12 11 14]
 [12 13 11]]


In [4]:
print("addition de mat1 et mat2 : \n ", mat1 + mat2)
# print("addition de mat1 et mat2 : \n ", np.add(mat1, mat2)) => same shit

addition de mat1 et mat2 : 
  [[19 19 17]
 [19 12 21]
 [21 18 20]]


In [5]:
print("soustraction de mat1 et mat2 : \n ", mat1 - mat2)
# print("soustraction de mat1 et mat2 : \n ", np.subtract(mat1 - mat2)) => same shit

addition de mat1 et mat2 : 
  [[-11 -11  -5]
 [ -5 -10  -7]
 [ -3  -8  -2]]


### Produit matricielle

In [6]:
mat3 = np.random.randint(1,10,(2,3))
print("mat3 : \n", mat3)
mat4 = np.random.randint(11,20,(3,2))
print("\n mat4 : \n", mat4)

mat3 : 
 [[9 3 7]
 [5 4 7]]

 mat4 : 
 [[13 15]
 [17 16]
 [13 18]]


In [11]:
print("produit matricielle : \n", np.matmul(mat3, mat4))
# print("produit matricielle : \n", np.dot(mat3, mat4)) => same shit

produit matricielle : 
 [[259 309]
 [224 265]]
